### ISSUE TITLE
Have experience with GitHub & Git

### ISSUE THREAD

**Issue by krashish8** [krashish8/GSoC-pgRouting#1]
- [x] Fork the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository
- [x] activate issues in your fork
- [x] open an issue in your fork and put this content on the issue
- [x] Clone your fork repository in your computer
- [x] Create remote named `upstream` pointing to https://github.com/pgRouting/pgrouting
- [x] checkout to the master branch of `upstream`
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] put link of branch on pgRouting gitter chat
- [x] put link of issue on pgRouting gitter chat

**Comment by krashish8** [comment]
Screenshots of completing this task:

![Screenshot from 2020-02-24 11-49-41](https://user-images.githubusercontent.com/39548570/75132270-579ee580-56fc-11ea-8af0-b81197efb1a2.png)
![Screenshot from 2020-02-24 11-50-16](https://user-images.githubusercontent.com/39548570/75132274-5a99d600-56fc-11ea-9df5-91dbb60c288d.png)

**Comment by cvvergara** [comment]
This is your fork, so its ok.
but on other's people forks, dont put images of instructions and results.

This task is passed, close this issue please

**Comment by krashish8** [comment]
> This is your fork, so its ok.
> but on other's people forks, dont put images of instructions and results.
> 
> This task is passed, close this issue please

Okay, I’ll make sure this doesn’t happen again.
