### ISSUE TITLE
Build locally pgRouting

### ISSUE THREAD

**Issue by krashish8** [krashish8/GSoC-pgRouting#2]
- [x] Install requirements
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] build locally pgRouting
- [x] put link of issue on pgRouting gitter chat

**Comment by krashish8** [comment]
Screenshot of Local Build:

![Screenshot from 2020-02-24 13-31-50](https://user-images.githubusercontent.com/39548570/75136508-f8949d00-570a-11ea-8adb-f31800c45931.png)
![Screenshot from 2020-02-24 13-32-12](https://user-images.githubusercontent.com/39548570/75136556-13ffa800-570b-11ea-9ffd-c535d5f65638.png)
![Screenshot from 2020-02-24 13-29-04](https://user-images.githubusercontent.com/39548570/75136560-16fa9880-570b-11ea-8bbe-34640637dd9b.png)
![Screenshot from 2020-02-24 13-30-26](https://user-images.githubusercontent.com/39548570/75136561-182bc580-570b-11ea-81a9-ded9f7c8a53d.png)

**Comment by krashish8** [comment]
Screenshot of Local Build:

![Screenshot from 2020-02-24 13-31-50](https://user-images.githubusercontent.com/39548570/75136603-3691c100-570b-11ea-902d-8eb92f14213a.png)
![Screenshot from 2020-02-24 13-32-12](https://user-images.githubusercontent.com/39548570/75136631-4ad5be00-570b-11ea-82a3-d657ca3b770e.png)
![Screenshot from 2020-02-24 13-29-04](https://user-images.githubusercontent.com/39548570/75136634-4c9f8180-570b-11ea-9f93-ce525a676ff3.png)
![Screenshot from 2020-02-24 13-30-26](https://user-images.githubusercontent.com/39548570/75136636-4d381800-570b-11ea-919d-0583fea81fb1.png)

**Comment by cvvergara** [comment]
cant you copy/paste words?

This task is passed, please close this issue

**Comment by krashish8** [comment]
> cant you copy/paste words?

I thought screenshots would be better proof of completing the task.
Anyway, I'll make sure to copy/paste next time.
