### ISSUE TITLE
Get familiar with C++

### ISSUE THREAD

**Issue by krashish8** [krashish8/GSoC-pgRouting#3]
- [x] https://www.youtube.com/watch?v=eidEEmGLQcU
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=u5senBJUkPc
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=YnWhqhNdYyk
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=1OEu9C51K2A
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=xnqTKD8uD64
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=86xWVb4XIyE
  - [x] Make Report

**Comment by cvvergara** [comment]
In this one, the report is handwritten. So please take a picture and of your report(s) and paste the image. Please do one comment per video report

**Comment by krashish8** [comment]
**Report 1:** CppCon 2015: Michael VanLoon “STL Algorithms in Action ”

![202003021448511000](https://user-images.githubusercontent.com/39548570/75662738-9bae5f00-5c95-11ea-9921-c7e80a459d28.jpg)

**Comment by krashish8** [comment]
**Report 2:** CppCon 2015: T. Winters & H. Wright “All Your Tests are Terrible..."

![202003021448511001](https://user-images.githubusercontent.com/39548570/75662848-cef0ee00-5c95-11ea-9f96-26630d621548.jpg)

**Comment by krashish8** [comment]
**Report 3:** CppCon 2015: Bjarne Stroustrup “Writing Good C++14”

![202003021448511003](https://user-images.githubusercontent.com/39548570/75662900-ec25bc80-5c95-11ea-8e61-3b7acd22769e.jpg)

**Comment by krashish8** [comment]
**Report 3:** CppCon 2015: Kate Gregory “Stop Teaching C"

![202003021448511002](https://user-images.githubusercontent.com/39548570/75663067-3ad35680-5c96-11ea-9630-84a9ebe916b9.jpg)

**Comment by krashish8** [comment]
**Report 4:** CppCon 2015: Bjarne Stroustrup “Writing Good C++14”

![202003021448511003](https://user-images.githubusercontent.com/39548570/75663118-5179ad80-5c96-11ea-8eb1-9b797178a56e.jpg)

**Comment by krashish8** [comment]
**Report 5:** CppCon 2014: Herb Sutter "Back to the Basics! Essentials of Modern C++ Style"

![202003021448511004](https://user-images.githubusercontent.com/39548570/75663184-6b1af500-5c96-11ea-8e0c-dcdb30657113.jpg)

**Comment by krashish8** [comment]
**Report 6:** Bjarne Stroustrup - The Essence of C++

![202003021448511005](https://user-images.githubusercontent.com/39548570/75663231-7e2dc500-5c96-11ea-87ab-2ca6bf81d990.jpg)

**Comment by krashish8** [comment]
@cvvergara Please review

**Comment by cvvergara** [comment]
Pass
