### ISSUE TITLE
Start working on the proposal

### ISSUE THREAD

**Issue by cvvergara** [krashish8/GSoC-pgRouting#6]
You have passed 2 out of 3 tests, now its time to start working on the proposal

Please always read carefully

* https://summerofcode.withgoogle.com/organizations/5173753207586816/
* https://github.com/pgRouting/pgrouting/wiki/GSoC-Ideas%3A-2020

Don't forget that new ideas are always welcome

* [x] Open a shared file with comment capabilities to anyone with the link
* [x] Put the suggested template
  * [x] start filling with basic information
* [x] share link in gitter
* [x] put link in comment on this issue

**Comment by krashish8** [comment]
Here's the public link of my proposal: https://docs.google.com/document/d/16M1idfX_G8OkILx5KbPaEzGNn3AaD0Qo9yqjsF_Wz20/edit?usp=sharing

**Comment by krashish8** [comment]
I'm currently working on the "Detailed Proposal" section and have completed all other sections of the proposal, except Future Work and References. Also, I've completed the **Undirected Depth First Search** algorithm in the Detailed Proposal section.

Please review the work I did till now @cvvergara. I'd be grateful for any feedback/criticism.

Link: https://docs.google.com/document/d/16M1idfX_G8OkILx5KbPaEzGNn3AaD0Qo9yqjsF_Wz20/edit?usp=sharing

**Comment by krashish8** [comment]
I have completed the unfinished works in the proposal. I think it is complete now, though many changes may still be required. Please review @cvvergara so that I can make the modifications accordingly.

Link is mentioned above.
